### ISSUE TITLE
Display event over three day continuously

### ISSUE THREAD

**Issue by Vanco** [alamkanak/Android-Week-View#150]
If event over three days, the weekview only display in start day and end day, but omit the over days.

**Comment by lolobosse** [comment]
Yes, I read your PR, seems to be fine but I would you remove the check for unicity of an apt

**Comment by Vanco** [comment]
We have encounter two problems when we use the WeekView.  
1. When async retrieve data from remote server in the `onMonthChange`, there no data get displayed.
2. it we have a three day appointment, only the start and end day get displayed.

I have fixed the 2. 

For the 1, there is no direct way to support the async call in the `onMonthChange`. I have to call the `notifyDatasetChanged` when the async callback to trigger the data refresh. but this will trigger the `onMonthChange` call again.  Two avoid call remote server in the second time, I make a cache to store the data in my Activity, and just feed the data when the second time call `onMonthChange`.   But the WeekView will fetch 3 month data when it first time create. this will call 9 times `onMonthChange`, and put duplicate event in `List<EventRect>`, and the display mass.  To avoid the duplicate, I make unicity check, and add the `equels` and `haschCode` method. this will help me to check unicity, and make a `Set<WeekViewEvent>` cache in the Activity, this two method is very helpful to Identify WeekViewEvent.

**Comment by lolobosse** [comment]
You're right, I also using this unicity check in production but I already proposed a PR for this (was thinking at that time that it was a bug) and @alamkanak explained me that I wrongly use the lib (what was true). So I would split your PR in two: one for unicity check, the other for the 3+ days events (I find this one great :smile: :+1: :tada: 

And I think the event 3+ days will be merged :tada: :balloon: :tada:

**Comment by azfaarks** [comment]
@Vanco  how you fixed the problem 2 ?

**Comment by azfaarks** [comment]
@Vanco  i am facing the same problem can you help me out please.

**Comment by caske33** [comment]
@azfaarks https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158

**Comment by sergiiz** [comment]
Hi, could you please confirm if a three day appointment problem is fixed?
Still got it on version 1.2.3

**Comment by azfaarks** [comment]
@sergiiz yes it is solved in https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158

**Comment by sergiiz** [comment]
@azfaarks thanks, but it seems that link you sent is about UI-thread problem. And what about 3-days case?

If I set the following changes to code of sample in version 1.2.3 - still have the calendar being filled only for the first and for the last days, but days between it are empty.
```java
Calendar startTime = Calendar.getInstance();
startTime.set(Calendar.HOUR_OF_DAY, 3);
startTime.set(Calendar.DAY_OF_MONTH, 15); // this line was added 
startTime.set(Calendar.MINUTE, 0);
startTime.set(Calendar.MONTH, newMonth-1);
startTime.set(Calendar.YEAR, newYear);
Calendar endTime = (Calendar) startTime.clone();
endTime.add(Calendar.HOUR, 1);
endTime.set(Calendar.DAY_OF_MONTH, 19); // this line was added
endTime.set(Calendar.MONTH, newMonth-1);
WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
event.setColor(getResources().getColor(R.color.event_color_01));
events.add(event);
```
<img width="436" alt="screenshot 2015-08-18 19 47 20" src="https://cloud.githubusercontent.com/assets/3374292/9337848/05fc6c96-45e2-11e5-993e-460cb6316d61.png">

**Comment by caske33** [comment]
That is indeed a known bug and a PR is waiting to be merged.

**Comment by caske33** [comment]
This is now fixed in 1.2.4
