### ISSUE TITLE
Navigating between days very jerky in version 1.2.4 compared to before

### ISSUE THREAD

**Issue by wwahmed** [alamkanak/Android-Week-View#231]
This is an excellent library that I am trying to incorporate into a demo app and have noticed a degradation in experience between after upgrading from version 1.2.3 to 1.2.4.

I am attaching two videos with this issue. First video is showing how navigating between days is very jerky. Sliding left and sliding right results in 'oversliding' or 'undersliding', which is then compensated by the app by automatically jumping to the nearest day. It might have been a desired behavior, but as you can see in the video, for the most common use case of user going from day to day, it makes for a very jerky and unsettling experience. 

Now compare this to the experience in the older version, which can be seen in the second video. As soon as you slide to left or right, the view smoothly scrolls to that day. If we flick very fast, it may scroll to a few days back and forth, but the experience is very smooth, very predictable. 

Is there a way to get the old behavior back, or is this on purpose? If it's on purpose, would anyone mind pointing out the relevant change that is causing this, so I can consider overriding it?

Thank you, and many kudos for an excellent job done. 

Videos: 

Old Version: (Smooth Behavior) : http://gfycat.com/WelllitWideeyedGenet

New  Version:(Jerky Behavior) http://gfycat.com/ElasticExhaustedArchaeocete

**Comment by caske33** [comment]
See #200 

@marunjar Do you think we can play a little more with the speed of the animations to make this smoother? It seems like the biggest problem is that it takes to long to "clip" to a day or that the clipping is too fast.

**Comment by marunjar** [comment]
indeed, this is an issue resulting from optimizing scroll and fling performance.
i'm on it.

we can try playing around with scroll time, i think clipping days is a little to fast when scrolling.
the second fix can be done with the scrolling direction, i accidentally removed this and now after scrolling the day is clipped to the nearest one and not to the next one in scrolling direction.

**Comment by marunjar** [comment]
i tried to fix scroll behaviour with #232, maybe someone else can test it

**Comment by wwahmed** [comment]
I have tested it and while it has slightly improved, it's nowhere close to as smooth and fluid as it used to be. 

On the old version, a slide or flick in horizontal direction would result in a CONTINUOUS smooth motion of the view, resulting in page change very similar to android view pager that we are always used to. 

Even in this latest fix #232, the view slides, then stops, waits for a bit and then snaps. The one smooth continuous motion is still absent. 

I am but just one user so this feedback may not amount to much, but I didn't experience any performance issues with the old version of the library. The fluid view movements were a big showcase for the library, and I'd much rather go back to the old behavior than get the performance improvements (but I never noticed any performance issues to begin with anyway, even on very weak devices). 

Video showing that it's still not as smooth: http://gfycat.com/DefiniteCleverIndigobunting

**Comment by wwahmed** [comment]
Adding to the previous comment.. Depending on where the view is when you release you'd finger during sliding, sometimes it jumps by two days and sometimes by one. This may be subjective, but this really is significant degradation of consistent, predictable behavior from release 1.2.3

**Comment by marunjar** [comment]
@wwahmed that sounds like you dont wan't the flick gesture enabled, fling has no CONTINUOUS scroll speed but decreasing one that you can see in your app.

the behaviour in 1.2.3 was following: 
when you end scrolling the view moves to next day in scrolling direction. 
but fling was a little bit jerky, it blocks like mentioned in  #139: the view scrolls and if you end scroll the animations stopped and then started the fling. 

now it is changed a little bit: scroll works as intended but if you do a fling it immediately goes on into the fling animation. 

one problem was there before and is also now: fling scrolls to a final position that we can't really predict. So after fling has finished we have to snap to a day. 
in 1.2.4 this was done by going to the nearest day, can be left or right.
 
With #232 it is like in 1.2.3: after fling the view scrolls to next day in the scrolling direction.
This is also the problem why sometimes it seems to jump two days. 
If your fling end in the second day it will go to this one because we snap to next day in specific direction now.
The other option is to go back to snapping to next day, but then you can't use your fling on day view because if there was not enough motion the view will also snap back onto your visible day.

but we're working on it

**Comment by wwahmed** [comment]
@marunjar Thanks for the detailed response. I will try the various scenarios your outlined to provide you feedback you can use. I'd venture that the balance of compromises should title in the favor of what a user is most likely or most often going to do. It could be subjective, but I imagine than more often than not, user is interested in adjacent days, rather than many days later. So it might be useful to default the behavior to favor the adjacent day navigation scenario. And if necessary, the alternative behavior can be made configurable?

**Comment by wwahmed** [comment]
HI @marunjar 

So I went back and played with it more, and also played around with Google Calendar, and here are my observations and suggestions. 

Please note that I used 1-Day view for my tests. 

1. In the latest pull request, #232,  the scroll behavior is not yet like it used to be in release 1.2.3. Two differences are 
  - (a) On 1.2.3, fling behavior didn't kick off when we were only scrolling. In the latest pull request, a scroll ends up being a fling just too often. 
  - (b) Even when  a scroll is processed, in 1.2.3, it used to be a continuous motion with snapping at the end. And now, the view waits for the scrolling to stop, pause for a few milliseconds, and then snap to the day in the scroll direction. The scroll behavior of 1.2.3 was more appealing and very similar to the behavior of Android View pager (a plus in my judgement). 

2. I inspected the Google calendar behavior and what that does is regardless of whether you scrolled or flinged, it moves to the 'next page' or 'previous page'. The definition of page depends on the view mode. In one day mode, you always advance or go back by one day. Whereas in the 7 day mode, you advance to the next page showing the next 7 days or back to page showing the previous 7 days. But it is never a continuous 'undetermined' range where we expect the user to observe the flinging motion, and try to stop it when he's ready. 

So my question, or suggestion to you is, whether the following look like a goo idea: 

1. We can expose a parameter to enable/disable fling. That way it's an option for the developer to choose the desired behavior. 

2. If fling is not enabled, then make the scroll  behavior (not talking about fling anymore), match the behavior we had in 1.2.3, where scrolling left or right smoothly snapped to next or previous day, as opposed to what we have today: scroll starts, scrolling ends, there is a few ms pause, and then the view snaps to next or previous day. Very jittery. 

What do you think?

**Comment by caske33** [comment]
@wwahmed What I like to point out too, is that in the previous version with multiple days and full scrolling speed, sometimes the scrolling would jump 3+ days or so, so the behaviour was really not solid enough for multiple days. So I think we have to find a solution that covers both cases then. Because just supporting 1 day is not enough in my opinion.

You can basically disable fling by the xHorizontalScrollingSpeed attribute though. Set it to a low value (I believe 0.1 is low enough) and it shouldn't fling anymore. (at least it didn't in 1.2.3).

**Comment by wwahmed** [comment]
@caske33 thanks for the suggestion -- making the horizontal speed 0.1f did help. However, there is one more thing to fix yet -- which is, the 'pause-then-snap' behavior. 

If I leave the speed set to 1.0f, then this results in the behavior where the view scrolls horizontally, then pauses for a few ms, and then snaps. 

At low speed of 0.1f, it makes the experience even weirder. Because the speed is slow and distance covered in scroll is less, the whole pause-then-snap behavior makes it look like the view is lagging in responding to scroll gesture. 

Do you know what part of the implementation introduced this pause-then-snap behavior in 1.2.4. In the old release, it wasn't there or at least wasn't noticeable.

**Comment by marunjar** [comment]
the pause is there because fling isn't really disabled.
onFling is called every time but mHorizontalScrollingSpeed just scales the velocity used for fling. 
So scrolling isn't that fast but it also slows down and when finished there is the pause then snap again.

i think disabling fling like in #174 would be a better than just setting mHorizontalScrollingSpeed to a low value.

@wwahmed can you give it a try and add the switch after the mZooming check? So it returns immediately and do no fling at all.

```
@Override
        public boolean onFling(MotionEvent e1, MotionEvent e2, float velocityX, float velocityY) {
            if (mIsZooming)
                return true;

            switch (mCurrentScrollDirection) {
                case LEFT:
                case RIGHT:
                    return true;
            }

            mScroller.forceFinished(true);

            mCurrentFlingDirection = mCurrentScrollDirection;
```

The behaviour has changed with #192, the pause wasn't noticeable for one day view but for multi day view.

**Comment by wwahmed** [comment]
@marunjar @caske33 

I took @marunjar suggestion, changed the scrolling speed back to 1f, and used the snippet he suggested and now the one day view is behaving better.... on horizontal scroll, it snaps to next or previous day in a smooth continuous motion. Perfect. 

The same is true for mutli day views also, except on multiday views, it also srolls left or right by ONE day. I like the google calendar view which scrolls left or right by ONE page, so on multi day views, if you scroll next, you get the next page with next set of days. (3 days if you are in 3 days views for example). 

I am going to try and emulate that behavior. If you have any tips, watchouts, or suggestions for how to best go about it, I'll appreciate your feedback. 

I will also be sticking around to see what other changes you want to make to scrolling behavior and do testing and provide you feedback, since you mentioned that it's still a work in progress. 

thanks.

**Comment by caske33** [comment]
@wwahmed That behaviour is not always what you want though either. It should be configurable whether or not you want to scroll by page or by day. Because some people prefer scrolling by day.

**Comment by caske33** [comment]
Should be fixed in 1.2.5 thanks to #232

**Comment by entropitor** [comment]
@marunjar I'm still getting some complaints about this scroll in the one-day view. Would it be possible to have a faster animation if only one day is displayed and the current for more days?

**Comment by wwahmed** [comment]
@caske33 @marunjar 

What I found out was that though #232  is supposed to fix it - it still wasn't fixed, and I had to re-apply the fix manually as was originally proposed for @marunjar  in his post above from Dec 17, 2015

#232 looks look it was supposed to be fixing it the same way - but maybe something wasn't completely done and the fix is not really taking effect. 

I am travelling right now otherwise would look into and offer help on why #232 wasn't taking effect. S o for now, I am using @marunjar  suggestion from Dec 17th post. It's still not as smooth and fast as it used to be, but bearable.

**Comment by marunjar** [comment]
@caske33 that's possible, any suggestions for scroll duration? 

@wwahmed have you set horizontalFlingEnabled to false? That should have the same effect as the 'fix' you mentioned.

At the moment scroll speed is set to 500ms for a full day, maybe that's too slow. 
How about providing a property so users can set their own scroll duration? 

Also you can play around with the duration in goToNearestOrigin()

```
   if (nearestOrigin != 0) {
            // Stop current animation.
            mScroller.forceFinished(true);
            // Snap to date.
            mScroller.startScroll((int) mCurrentOrigin.x, (int) mCurrentOrigin.y, -nearestOrigin, 0, (int) (Math.abs(nearestOrigin) / mWidthPerDay * 500));
            ViewCompat.postInvalidateOnAnimation(WeekView.this);
        }
```

**Comment by entropitor** [comment]
I think a custom duration is probably a good idea. Although the default value should also be tweaked. It's hard to tell without viewing it, but I would guess a value between 100 and 300 ms should be ok.

**Comment by marunjar** [comment]
i change it with #276
it will use the default scroll duration of 250ms and there are also properties for setting a custom scroll duration

if anything else needs to be changed please let me now

**Comment by cnbscience** [comment]
This doesn't seem to have fixed, I am facing similar problems on API 28.  I have made all the changes that is proposed here and testing it on a physical android tablet. I am not sure if I should continue using this library since it is going to be part of production it could cause major customer problems.
