### ISSUE TITLE
getFirstVisibleDay sometimes returns wrong day.

### ISSUE THREAD

**Issue by EmanueleHB** [alamkanak/Android-Week-View#54]
I've got a button wich calls goToDate() and the date is calculated starting from getFirstVisibleDay(). The problem is that getFirstVisibleDay() sometimes returns a Calendar instance off by one day, which causes the calculation to fail.

**Comment by caske33** [comment]
Can you provide more information? (on how to recreate the bug)

How many days are you showing?
What are you doing before the bug occurs?
Are you sure that there is not even a tiny little part of the day showing? (there's still a bug where on swiping the library gets stuck between 2 days)

**Comment by hellchoseme** [comment]
Right, sorry about that, here's the code:
'''java
Calendar firstday = mWeekView.getFirstVisibleDay();

case R.id.action_fw:

                Calendar nextdate = (Calendar) firstday.clone();
                if(nextdate.get(Calendar.DAY_OF_YEAR) == firstday.get(Calendar.DAY_OF_YEAR)){
                    nextdate.add(Calendar.DAY_OF_YEAR, 1);
                }
                while (nextdate.get(Calendar.DAY_OF_WEEK) != Calendar.MONDAY) {
                    nextdate.add(Calendar.DAY_OF_YEAR, 1);
                }
                mWeekView.goToDate(nextdate);
                return true;
'''
The code makes the weekView go to the next monday.
I don't think that a part of the previous day is showing because it goes to it with goToDate().
I am showing 6 days.

Thanks a lot.

**Comment by caske33** [comment]
Hmm, this is definitly weird. It only seems to happen when going forward (I have tested it with my code which is similair), not when going backwards. 

Maybe the ceil from https://github.com/alamkanak/Android-Week-View/blob/master/library/src/main/java/com/alamkanak/weekview/WeekView.java#L392 has to do with it. I'm not sure but I'm guessing using Math.round there might fix this. Needs testing.

(I'm also guessing #53 will fix the onCreate thing. I don't have commit access so @alamkanak will have to merge that PR)

**Comment by Hugo-Pereira** [comment]
replace 
```
int leftDaysWithGaps = (int) -(Math.ceil((mCurrentOrigin.x+ getColumnGap()) / (mWidthPerDay + mColumnGap)));
float startFromPixel = mCurrentOrigin.x + (mWidthPerDay + mColumnGap) * leftDaysWithGaps +
                mHeaderColumnWidth;
```

with 

```
int leftDaysWithGaps = -(Math.round(mCurrentOrigin.x / (mWidthPerDay + mColumnGap)));
float startFromPixel = mCurrentOrigin.x + (mWidthPerDay + mColumnGap) * (leftDaysWithGaps-1) +
                mHeaderColumnWidth;
```

Tell me if this helps, I have been messing around with the library for a while now :\

**Comment by caske33** [comment]
While testing, I think the bug lies within goToDate and not in getFirstVisibleDay. 

@hellchoseme can you test my PR to see if it works for you?
(git clone this project from your app's root directory, merge my PR, add `include(':weekview:library')` to your settings.gradle and add a `compile project(':weekview:library')` instead of the `compile 'com.github.almakanak:android-week-view:version-number'`

**Comment by hellchoseme** [comment]
I merged your PR, it's still not working. Although the bug appears after a few more clicks than before.

**Comment by caske33** [comment]
Hmm, that's annoying. I'll take another look. I think it has something to do with numerical math stuff, so it's going to be annoying to debug :(

**Comment by caske33** [comment]
@hellchoseme I tried to reproduce the bug, but I can scroll all the way too June without it ever getting stuck. I'm not sure how to fix the bug (if it's even in the library/PR) without reproducing. Can you maybe provide more information on your setup? 
- How many days are you showing (still 6)?
- What day are you testing this
- On what day is it returning the wrong value?
- Any more information that you might think is relevant.

**Comment by caske33** [comment]
@hellchoseme I think it's fixed with my 2nd commit :D

**Comment by hellchoseme** [comment]
Hi I'm still having some issues. Sometimes getFirstVisibleDay() returns the day before. Also, I'm having a strange issue with this code:

```java
Calendar nextdate = mWeekView.getFirstVisibleDay();
                nextdate.add(Calendar.DAY_OF_YEAR, 1);
                while (nextdate.get(Calendar.DAY_OF_WEEK) != Calendar.MONDAY) {
                    nextdate.add(Calendar.DAY_OF_YEAR, 1);
                }
                mWeekView.goToDate(nextdate);
```

Sometimes the DAY_OF_WEEK value is different than the date displayed in time variable (expressed in milliseconds), ultimately breaking my code. Any clues on what could cause this behaviour? Thanks

**Comment by caske33** [comment]
Have you tried me latest commit too?

**Comment by hellchoseme** [comment]
I don't think, I'm on last alamkanak's merge. I'll try tomorrow.
